### ISSUE TITLE
Null Geodesics for Kerr & Schwarzschild Geometry

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#105]
🐞 **What bugs you?**
Null-geodesics is the path traced by light rays in 4-D space-time. We aim to calculate null geodesics around non-rotating (Schwarzschild) and rotating (Kerr) massive bodies given the initial conditions.
This feature would support the one of the celebrated phenomenons in GR, gravitational lensing.

🎯 **Goal**
  - Null geodesic in Kerr/Schwarzschild space-time
  - Plotting class for both Kerr and Schwarzschild null geodesics.

💡 **Possible solutions**
Papers for references :
  - https://arxiv.org/abs/1601.02063
  - https://www.aanda.org/articles/aa/abs/2004/36/aa0814/aa0814.html
  - http://www.math.mcgill.ca/gantumur/math599w17/project-kerr.pdf

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by ritzvik** [comment]
Some freely available repos related to the issue :
  - https://github.com/grtrace/grtrace
  - https://github.com/Varcho/GeneralRelativity

**Comment by ritzvik** [comment]
Units `c=1,G=1` handling table https://en.wikipedia.org/wiki/Geometrized_unit_system

**Comment by ritzvik** [comment]
Don't know if this would help https://github.com/martinberoiz/BHBattle, but it says it uses Kerr Null-geodesic generator.

**Comment by ritzvik** [comment]
Related repo : https://github.com/rantonels/starless

**Comment by ritzvik** [comment]
A related paper : https://iopscience.iop.org/article/10.1088/0067-0049/207/1/6

**Comment by ritzvik** [comment]
https://iopscience.iop.org/article/10.1088/0004-637X/696/2/1616

**Comment by shilpi1958** [comment]
YNOGK
Paper: https://arxiv.org/pdf/1305.1250.pdf
Code : http://www1.ynao.ac.cn/~yangxl/yxl.html

**Comment by VedantParanjape** [comment]
Hey, i am coming from gsoc page, I'm am from electronics engineering background, with decent coding skills, does this problem idea require extensive physics knowledge?

**Comment by ritzvik** [comment]
Willingness to immerse yourself in physics during the community bonding period and first 1-2 weeks would do :)

Regards,
Ritwik

**Comment by VedantParanjape** [comment]
I love physics and maths, i had 70 in maths and physics each in JEEA 2018(Is this irrelevant?).

From coding aspect which tools will i use, i have decent experience in C++ and python !

Regards, 
Vedant

**Comment by shreyasbapat** [comment]
Hi @VedantParanjape , Can you please join the chatroom? We can have a detailed description over there!

**Comment by VedantParanjape** [comment]
Yeah okay

**Comment by ganeshtero** [comment]
As the project is touching the concept of Gravitational lensing , i guess what if we could add an addon feature of determining the existence of dark matter substructure , from gravitational lensing simulations , we could prove the existence of dark matter from it? #newfeature

**Comment by GTron-1729** [comment]
As the project is touching the concept of Gravitational lensing , i guess what if we could add an addon feature of determining the existence of dark matter substructure , from gravitational lensing simulations , we could prove the existence of dark matter from it? #newfeature

**Comment by ritzvik** [comment]
> As the project is touching the concept of Gravitational lensing , i guess what if we could add an addon feature of determining the existence of dark matter substructure , from gravitational lensing simulations , we could prove the existence of dark matter from it? #newfeature

As discussed over chats, a detailed (new) issue with relevant links and references(especially pre-existing codes or published research papers) would be highly appreciated. The description here is quite vague. Hope you would understand :)

**Comment by GTron-1729** [comment]
Actually it is just an idea , so it will require some time to collect detailed info , papers and relevant code for it , if i get it i will surely share it. @ritzvik

**Comment by Suyog7130** [comment]
This is the main issue for the GSoC 2020 project on Null Geodesics, isn't it? 

Now, as far as I understand it, the two main papers noted above are the main codes available presently for generating the Null Geodesics for BH geometries. One is written in C and the other FORTRAN. I understand that the attempt is to reproduce the similar code written in python. One can of course simply translate the codes to python, however, unique features of this language like OOPs are gotta be utilised. So, one class each for a Kerr and a Schwarzschild Geometry. 

Generation of a geodesics involves solving some differential equations given the initial conditions. In the available codes, one does it using the the RK5 method while the other first transforms all the variables to be some function of a single parameter. Both of these things can be tried. All the other things mentioned can be started once the geodesics are obtained. 

I would like to work on solving the six equations using RK5 or ADI method; by writing the code for it. Then this can be expanded for both of the cases, angular momentum J = 0 or otherwise. Later we can extend it to included other spacetime geometries as well. For instance, one useful extension will be to simulate (2D) how light bends around two colliding BHs, right after the inspiral phase and to see the changes as time progresses. The recent GW observation was of just such a collision taking place head on. 

Has somebody initiated work in this direction? The issue dates from last year, surely there would be things completed. If so, can you direct where the progress done is detailed.

**Comment by ritzvik** [comment]
@Suyog7130 , as far as your understanding goes, you have gotten the problem and approaches quite correctly. Currently, no significant work has been done on this. I would advise you to start working on it, if and when you are selected for the GSoC

**Comment by Suyog7130** [comment]
@ritzvik Sure Man. 
However, I like the project very much. And it is a damn nice learning opportunity; So I guess I am gonna work on it regardless of the GSoC selection. 
It is open source, so anybody can contribute. And I would love to be part of the project.

**Comment by ritzvik** [comment]
@Suyog7130 , that's very much appreciated. After you go through the papers thoroughly, discussion could be done in the chatroom.

**Comment by JeS24** [comment]
> ...Later we can extend it to included other spacetime geometries as well. For instance, one useful extension will be to simulate (2D) how light bends around two colliding BHs, right after the inspiral phase and to see the changes as time progresses. The recent GW observation was of just such a collision taking place head on.

Simulating a binary BH system is an intractable problem for now, because there is no known metric for such systems. But certainly, it is an interesting problem.
