### ISSUE TITLE
Simulate binary Black Hole mergers

### ISSUE THREAD

**Issue by ritzvik** [einsteinpy/einsteinpy#149]
🎯 **Goal**
Approximate simulations for Binary Black hole mergers is possible as exact solutions can take even days in a HPC.

💡 **Possible solutions**
Related Github Repo : https://github.com/vijayvarma392/binaryBHexp
Related paper : https://arxiv.org/abs/1811.06552

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #149`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by spino17** [comment]
There is already an issue #103 related to the adaptive mesh refinement algorithm which is yet to be implemented and would cover a large class of compact objects other than just black hole merger and thus would be more suitable to implement the binary merger system under that module as a part rather than an independent issue as this can break the generality of the module. So it is better to close this issue for now.

**Comment by ritzvik** [comment]
@spino17 thanks for pointing this out. As recommended, I'm closing this issue. My sincerest apologies.
