### ISSUE TITLE
Outdated Documentation?

### ISSUE THREAD

**Issue by AndriusT** [einsteinpy/einsteinpy#580]
Hi, 

Thanks for the amazing code. I was trying it out today, but unfortunately a lot of the documentation seems to be outdated. Specifically, the following pages do not work with the newest version of the code: 

https://docs.einsteinpy.org/en/latest/examples/Visualizing%20Event%20Horizon%20and%20Ergosphere%20%28Singularities%29%20of%20Kerr%20Metric%20or%20Black%20Hole.html
https://docs.einsteinpy.org/en/latest/examples/Using%20Geodesics%20%28Back-ends%20%26%20Plotting%29.html

Is it a problem on my side, or is the documentation indeed outdated? 

Thanks!

Andrius

**Comment by JeS24** [comment]
@AndriusT Thanks for opening the issue. Which version of EinsteinPy are you using?

**Comment by JeS24** [comment]
@AndriusT Thanks for adding the details. This issue is related to #574. Apparently, the package on PyPi is outdated, while the [GitHub Release](https://github.com/einsteinpy/einsteinpy/releases/tag/v0.3.1) has the updated code, which has led to a mismatch between the documentation (up to date) and the actual PyPi-distributed code (obsolete). For the time being, you can download the [.zip archive](https://github.com/einsteinpy/einsteinpy/archive/v0.3.1.zip) or the [tarball](https://github.com/einsteinpy/einsteinpy/archive/v0.3.1.tar.gz) from the GitHub Release page and install it as follows:

1. Extract the .zip or the tarball.
2. In a terminal window, `cd` to the extracted folder (`einsteinpy-0.3.1/`).
3. Run `pip install .` (Note the dot, ".", that refers to the current folder)

All the tutorials and the documentation on the EinsteinPy website should be functional now.

**Comment by JeS24** [comment]
@shreyasbapat This issue is urgent.

**Comment by shreyasbapat** [comment]
Hi @AndriusT ! Thanks for bringing this to our notice. For now, please follow the steps told by @JeS24 . We will fix it ASAP!

**Comment by AndriusT** [comment]
Thanks!

I have installed the newest version and can now confirm that the relevant imports work.

I have tested the geodesic example (https://docs.einsteinpy.org/en/stable/examples/Using%20Geodesics%20%28Back-ends%20%26%20Plotting%29.html) and, unfortunately, it still does not seem to work. In particular, when defining the Geodesic class instance, it requires a 'metric' and 'metric_params', which are not defined in the example.

**Comment by JeS24** [comment]
> I have installed the newest version and can now confirm that the relevant imports work.

Great.

> I have tested the geodesic example (https://docs.einsteinpy.org/en/stable/examples/Using%20Geodesics%20%28Back-ends%20%26%20Plotting%29.html) and, unfortunately, it still does not seem to work. In particular, when defining the Geodesic class instance, it requires a 'metric' and 'metric_params', which are not defined in the example.

You are looking at the docs for "stable" (v0.3.1). Since you are using the "latest" or dev version (v0.4.dev0), please peruse the docs for "latest". You can switch between docs by clicking on this screentip at the bottom right of the docs website:
![image](https://user-images.githubusercontent.com/31299799/111025821-c8e72e80-840c-11eb-84f9-e75c40bf9035.png)
![image](https://user-images.githubusercontent.com/31299799/111025822-cab0f200-840c-11eb-96fd-fda9e192a51e.png)

There were some significant updates to the `Geodesics` module between v0.3.1 and v0.4.dev0.

**Comment by AndriusT** [comment]
Sorry, that was my bad. Now it all works. Thanks!

**Comment by shreyasbapat** [comment]
Have made a release for the project just now. Hope this all will be fixed
