### ISSUE TITLE
the terms of the Ricci Tensor are tangled

### ISSUE THREAD

**Issue by AfnanAlsaati** [einsteinpy/einsteinpy#588]
Hi everyone, when i print the ricci tensor in pyhton (with sympy and einteinpy) the results are tangled
how can I resolve this ? 
I really don't understand how I should read this
If I can have some help please 
in this picture, this is for the Ricci scalar
![image](https://user-images.githubusercontent.com/83760863/117853029-3afeb700-b288-11eb-9f52-a0899a095084.png)

**Comment by shreyasbapat** [comment]
Hey @AfnanAlsaati , can you share some code snippet which can help me understand the problem well?

**Comment by AfnanAlsaati** [comment]
Hi @shreyasbapat,
Yes of course, 
![image](https://user-images.githubusercontent.com/83760863/118564146-174bdd00-b770-11eb-815a-12f7234c5935.png)


I finally do my work on Notebook. I dont know why but in Python I can't display well the tensor like I said before

**Comment by shreyasbapat** [comment]
Thanks @AfnanAlsaati . I will get back to you in a day or two on this.

**Comment by shreyasbapat** [comment]
Also, would be great if the code snippet can be placed in a Github Gist or something like that. Because it helps understand the problem better.

**Comment by AfnanAlsaati** [comment]
Hi @shreyasbapat , Ok ! Tank you 

This is my display of the tensor on Jupyter(notebook)  work well. It is only in python my problem.  I don't know why it don't work. Do you want that a copy and paste my python code ?

**Comment by JeS24** [comment]
Hey @AfnanAlsaati, thanks for opening this issue. Since the elements in the matrix are quite long, they are getting split into multiple lines. So, the terminal window is unable to fit the whole matrix, leading to symbols being tangled. Another issue is that Sympy usually cannot generate latex output in the terminal, because many terminals do not support the full Unicode character set (UTF-8) out-of-the-box. The most elegant solution is to use Jupyter notebook, either in a browser like you are doing, or in a code editor like Visual Studio Code.

That said, if you have to use python in the terminal, ensure that UTF-8 support is enabled and that you are using a terminal font that also supports UTF-8. The exact way to do this depends on your terminal.

I am closing this issue as resolved. Feel free to comment here, if you have any further questions.
