### ISSUE TITLE
The display of the Riemann Tensor

### ISSUE THREAD

**Issue by AfnanAlsaati** [einsteinpy/einsteinpy#590]
Hi everyone ! 

When I display the Riemann tensor I don't understand how EinsteinPy display it. The Riemann Tensor should be symmetric, so why the display shows that it is not ... ?

How should I read it ? 

 My Ricci tensor, christoffel, ricci scalar, ... etc  are all good. 

[Exam rattrapage RG 2021 ISAE.pdf](https://github.com/einsteinpy/einsteinpy/files/6510976/Exam.rattrapage.RG.2021.ISAE.pdf)

**Comment by AfnanAlsaati** [comment]
![image](https://user-images.githubusercontent.com/83760863/118867494-70884d80-b8e3-11eb-9db8-e18c15b6f21c.png)

**Comment by JeS24** [comment]
Thanks for opening the issue. This was a bug in `einsteinpy 0.3.1` which was fixed in `einsteinpy 0.4.0` (#577). Please upgrade to version 0.4.0 via `pip install --upgrade einsteinpy` and re-run the code. It should produce the correct output.

Also, to answer this question:
> When I display the Riemann tensor I don't understand how EinsteinPy display it. The Riemann Tensor should be symmetric, so why the display shows that it is not ... ? How should I read it ?

I have written a guide to tensor-indexing in EinsteinPy, that is available [here](https://github.com/einsteinpy/einsteinpy/wiki/Tensor-Indexing-in-EinsteinPy-Symbolic).
